app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
	// Authentication Routes
	Route::get('auth/login', ['as' => 'login', 'uses' => 'Auth\AuthController@getLogin']);
	Route::post('auth/login', 'Auth\AuthController@postLogin');
	Route::get('auth/logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@getLogout']);


// Admin Routes
    Route::group(['prefix'=>'admin'], function (){
        Route::get('/login',['uses'=>'Auth\AdminLoginController@showLoginForm','as'=>'admin.login']);
        Route::post('/login',['uses'=>'Auth\AdminLoginController@login','as'=>'admin.login.submit']);
        Route::post('/logout',['uses'=>'Auth\AdminController@logout','as'=>'admin.logout']);
        Route::get('/',['uses'=>'Auth\AdminController@index','as'=>'admin.dashboard']);
    });



    // Password Reset Routes
	Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
	Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
	Route::post('password/reset', 'Auth\PasswordController@reset');

	// Categories
	Route::resource('categories', 'CategoryController', ['except' => ['create']]);
	Route::resource('tags', 'TagController', ['except' => ['create']]);
	
	// Comments
	Route::post('comments/{post_id}', ['uses' => 'CommentsController@store', 'as' => 'comments.store']);
	Route::get('comments/{id}/edit', ['uses' => 'CommentsController@edit', 'as' => 'comments.edit']);
	Route::put('comments/{id}', ['uses' => 'CommentsController@update', 'as' => 'comments.update']);
	Route::delete('comments/{id}', ['uses' => 'CommentsController@destroy', 'as' => 'comments.destroy']);
	Route::get('comments/{id}/delete', ['uses' => 'CommentsController@delete', 'as' => 'comments.delete']);


	Route::get('blog/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');
	Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);
    Route::get('contact', ['uses'=>'PagesController@getContact','as'=>'contact']);
    Route::post('contact', 'PagesController@postContact');
    Route::get('marketing',['uses'=>'PagesController@getMarketing','as'=>'marketing']);
	Route::get('webfejlesztes', ['uses'=>'PagesController@getIt','as'=>'webfejlesztes']);
	Route::get('portfolio',['uses'=>'PagesController@getPortfolio','as'=>'portfolio']);
	Route::get('price',['uses'=>'PagesController@getPrice','as'=>'price']);
	Route::get('gdpr',['uses'=>'PagesController@getGdpr','as'=>'gdpr']);
	Route::get('/', 'PagesController@getIndex');
	Route::resource('posts', 'PostController');
});

Route::group(['middleware' => ['auth']], function () {

// Registration Routes
    Route::get('auth/register', 'Auth\AuthController@getRegister');
    Route::post('auth/register', 'Auth\AuthController@postRegister');


});

resources/views/partials/_footer.blade.php
<hr>

      <!-- Footer -->
      <section id="footer">
            <div class="container">

                  <div class="row">
                        <div class="col-md-12 text-center">
                              <p><a class="text-green ml-2"style="color: #57a544;" href="/gdpr">GDPR</a></p>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
                              <ul class="list-unstyled list-inline social text-center">
                                    <li class="list-inline-item"><a href="https://www.facebook.com/collettivohungary/" target="_blank"><i class="fa fa-facebook"style="color: #57a544;"></i></a></li>
                                    <li class="list-inline-item"><a href="https://www.instagram.com/collettivo_hungary/" target="_blank"><i class="fa fa-instagram"style="color: #57a544;"></i></a></li>
                                    <li class="list-inline-item"><a href="/contact" target="_blank"><i class="fa fa-envelope"style="color: #57a544;"></i></a></li>
                              </ul>
                        </div>
                        </hr>
                  </div>
                  <div class="row">

                        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                              <p class="h5">&copy Minden jog fenntartva. | 2018 | <a class="text-green ml-2"style="color: #57a544;" href="/">COLLETTIVO</a></p>
                        </div>
                        </hr>
                  </div>
            </div>
      </section>

      <!-- ./Footer -->

resources/views/partials/_head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<title>Collettivo | Online Marketing & Webfejlesztés @yield('title')</title>
<meta name="description" content="@yield('description')">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

<!-- Bootstrap -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
{{ Html::style('css/styles.css') }}

@yield('stylesheets')

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

resources/views/partials/_javascript.blade.php
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src="../../../public/js/main.js"></script>

resources/views/partials/_messages.blade.php
@if (Session::has('success'))
	
	<div class="alert alert-success" role="alert">
		<strong>Success:</strong> {{ Session::get('success') }}
	</div>

@endif

@if (count($errors) > 0)

	<div class="alert alert-danger" role="alert">
		<strong>Errors:</strong>
		<ul>
		@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
		@endforeach  
		</ul>
	</div>

@endif

resources/views/partials/_nav.blade.php
<!-- Default Bootstrap Navbar -->
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">COLLETTIVO</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav ">
        <li class="{{ Request::is('/') ? "active" : "" }}"><a href="/">Home</a></li>
        <li class="{{ Request::is('marketing') ? "active" : "" }}"><a href="/marketing">Marketing</a></li>
        <li class="{{ Request::is('blog') ? "active" : "" }}"><a href="/blog">Blog</a></li>
        <li class="{{ Request::is('webfejlesztes') ? "active" : "" }}"><a href="/webfejlesztes">Webfejlesztés</a></li>
        <li class="{{ Request::is('portfolio') ? "active" : "" }}"><a href="/portfolio">Portfolio</a></li>
        <li class="{{ Request::is('price') ? "active" : "" }}"><a href="/price">Áraink</a></li>
        <li class="{{ Request::is('contact') ? "active" : "" }}"><a href="/contact">Elérhetőség</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        @if (Auth::check())
        
        <li class="dropdown">
          <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello {{ Auth::user()->name }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{ route('posts.index') }}">Bejegyzések</a></li>
            <li><a href="{{ route('categories.index') }}">Kategóriák</a></li>
            <li><a href="{{ route('tags.index') }}">Címkék</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{{ route('logout') }}">Kijelentkezés</a></li>
          </ul>
        </li>
        
        @else
        
          <a href="{{ route('login') }}" class="btn btn-default btn-xs btn-login ">Bejelentkezés</a>

        @endif

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

resources/views/partials/cookies.blade.php
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/cookie-bar/cookiebar-latest.min.js?forceLang=hu&always=1"></script>

resources/views/partials/scroll_up.blade.php
<button onclick="topFunction()" id="myBtn" title="Go to top">    <i class="fa fa-2x fa-arrow-circle-up" style="color: #fff"></i>
</button>
<script>
    // When the user scrolls down 20px from the top of the document, show the button
    window.onscroll = function() {scrollFunction()};

    function scrollFunction() {
        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
            document.getElementById("myBtn").style.display = "block";
        } else {
            document.getElementById("myBtn").style.display = "none";
        }
    }

    // When the user clicks on the button, scroll to the top of the document
    function topFunction() {
        document.body.scrollTop = 0;
        document.documentElement.scrollTop = 0;
    }
</script>
<style>

    #myBtn {
        display: none;
        position: fixed;
        bottom: 20px;
        right: 30px;
        z-index: 99;
        font-size: 18px;
        border: none;
        outline: none;
        background-color: #87d37c;
        color: white;
        cursor: pointer;
        padding: 15px;
        border-radius: 4px;
        margin-bottom: 15px;
    }

    #myBtn:hover {
        background-color: #555;
    }
</style>